name: Purge JSDeliver Cache

on:
  push:
    branches: ["main"]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Purge jsDelivr cache
        # You may pin to the exact commit or the version.
        # uses: gacts/purge-jsdelivr-cache@71fc7e172e0ef9559bfd251f43d75cf39cbeedba
        uses: gacts/purge-jsdelivr-cache@v1.0.2
        with:
          # URLs for the cache purging (string|list)
          url: https://cdn.jsdelivr.net/gh/rogi29/openmd-test-repository/
          # Retry attempts (on the request failing) (integer)
          attempts: 3
